### ISSUE TITLE
Floating point exception (core dumped)

### ISSUE THREAD

**Issue by diklou** [Goldo02/gif_art_engine_for_nft#1]
Hello, 
When I run the main script, It doesn't work and I get this message in console :
`Floating point exception (core dumped) `

When I set the randomized bool to true, it works. I want to do it with rarity though. What do I need to cdo ? I checked if the sum of all rarities was 100.

**Comment by diklou** [comment]
My collection was 888, I set it to 900 and now it works ! thank you

**Comment by diklou** [comment]
My collection was 888, I set it to 900 and now it works ! thank you

**Comment by nourlive** [comment]
hi how to run it please
