### ISSUE TITLE
Having Difficulties running the program in windows

### ISSUE THREAD

**Issue by Dejanrobi** [Goldo02/gif_art_engine_for_nft#2]
I have installed both FFmpeg and MinGW.
I have tried running the program on windows but it is still not working.
I have gotten an error in the src folder (main.cpp) under time(NULL).

If you don't mind, would you please make a screen record of how you can run the program in windows and genenerate the GIFS.
Even if its just recording without any sound (screen recording).
You may upload to youtube then please share the link here.

I'll really appreaciate your help and make a donation.

**Comment by Goldo02** [comment]
U need to add this line on top of main.cpp and metadatafunction.cpp: " include<ctime> " or u can redownload the repository i fixed this

**Comment by Goldo02** [comment]
Redownload the repository i fixed this

**Comment by Goldo02** [comment]
And write me on discord, there i'm faster in responding ti u
